### ISSUE TITLE
Missing comma in image_utils.py

### ISSUE THREAD

**Issue by jasper-vaart** [hayabhay/megadetector-fastapi#4]
Hi hayabhay,

Nice repo!
There seems to be a missing comma in line 20 in `image_utils.py` between `Pink` and `Aqua`.

**Comment by hayabhay** [comment]
Thanks! Fixed! :) https://github.com/hayabhay/megadetector-fastapi/commit/4648f913999331e8a7e8f61b5136f4c51a99471d
